config:
  target: "-=endpoint_to_test=-"
  phases:
    - duration: 300
      arrivalRate: 400
  defaults:
    headers:
      content-type: "application/json"
  http:
    timeout: 60
  plugins:
    expect: {}
    ensure: {}
    metrics-by-endpoint:
      useOnlyRequestNames: true
    publish-metrics:
      - type: prometheus
        pushgateway: 'https://pushgateway-testnet.rpc.zetachain.com/-=CLOUDFLARE_UUID=-'
        tags:
          - 'type:loadtest'
          - 'testId:-=GITHUB_ACTION=-'
          - 'jobName:evm-performance-test'
  summary: true
  reports:
    - type: "html"
      filename: "artillery_report.html"
  logLevel: debug

scenarios:
  - name: web3_clientVersion
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "web3_clientVersion"
            params: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: web3_sha3
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "web3_sha3"
            params:
              - "0x68656c6c6f20776f726c64"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
          - notHasProperty: "{{ response.error }}"

  - name: net_version
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "net_version"
            params: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: net_listening
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "net_listening"
            params: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"
            - equals:
                - "true"
                - "{{ response.result }}"

  - name: net_peerCount
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "net_peerCount"
            params: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_chainId
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_chainId"
            params: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getStorageAt
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getStorageAt"
            params:
              - "latest"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getTransactionByBlockHashAndIndex
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getTransactionByBlockHashAndIndex"
            params:
              - "0xbd8bd16e5d4375ed4bab633c4fb8aca58fdf7ed6c340853b20cfa91ed9a3b9e1"
              - "0x0"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getTransactionByBlockNumberAndIndex
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getTransactionByBlockNumberAndIndex"
            params:
              - "latest"
              - "0x0"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getUncleByBlockHashAndIndex
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getUncleByBlockHashAndIndex"
            params:
              - "0xbd8bd16e5d4375ed4bab633c4fb8aca58fdf7ed6c340853b20cfa91ed9a3b9e1"
              - "0x0"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getUncleByBlockNumberAndIndex
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getUncleByBlockNumberAndIndex"
            params:
              - "latest"
              - "0x0"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_newFilter
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_newFilter"
            params:
              - fromBlock: "latest"
                toBlock: "latest"
                address: "0x81eF14691E9ea2f711cf56a9f0889c49C5Fe995a"
                topics: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getFilterChanges
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getFilterChanges"
            params:
              - "0xbd8bd16e5d4375ed4bab633c4fb8aca58fdf7ed6c340853b20cfa91ed9a3b9e1"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getFilterLogs
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getFilterLogs"
            params:
              - "0xbd8bd16e5d4375ed4bab633c4fb8aca58fdf7ed6c340853b20cfa91ed9a3b9e1"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_blockNumber
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_blockNumber"
            params: []
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getBlockByHash
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getBlockByHash"
            params:
              - "0x8716674e0acdbe87bab4595ecd33436f8a1a1b32fcda721362fe98dfc764affe"
              - true
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getBlockByNumber
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getBlockByNumber"
            params:
              - "latest"
              - true
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getBlockTransactionCountByHash
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getBlockTransactionCountByHash"
            params:
              - "0x8716674e0acdbe87bab4595ecd33436f8a1a1b32fcda721362fe98dfc764affe"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getBlockTransactionCountByNumber
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getBlockTransactionCountByNumber"
            params:
              - "latest"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getCode
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getCode"
            params:
              - "0x0cbe0dF132a6c6B4a2974Fa1b7Fb953CF0Cc798a"
              - "latest"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getTransactionByHash
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getTransactionByHash"
            params:
              - "0x1a363840b12fa22aae5920edf11e2c59dde5260ffe5c9bc108250fe8380f5e75"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getTransactionReceipt
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getTransactionReceipt"
            params:
              - "0x1a363840b12fa22aae5920edf11e2c59dde5260ffe5c9bc108250fe8380f5e75"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getLogs
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getLogs"
            params:
              - address: "0x0cbe0dF132a6c6B4a2974Fa1b7Fb953CF0Cc798a"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_getBalance
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_getBalance"
            params:
              - "0x735b14BB79463307AAcBED86DAf3322B1e6226aB"
              - "latest"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"

  - name: eth_estimateGas
    flow:
      - post:
          url: "/"
          json:
            id: 1
            jsonrpc: "2.0"
            method: "eth_estimateGas"
            params:
              - from: "0x239e96c8f17C85c30100AC26F635Ea15f23E9c67"
                to: "0x0cbe0dF132a6c6B4a2974Fa1b7Fb953CF0Cc798a"
          capture:
            - json: "$"
              as: response
          ensure:
            - statusCode:
                - 200
                - 201
          expect:
            - notHasProperty: "{{ response.error }}"