# This docker-compose redefine the services:
# - ZetaChain with 4 nodes to test performance
# - ZetaChain observer set with 4 clients to test performance

services:
  zetacore0:
    environment:
      - ZETACORED_REPLICAS=4

  zetacore1:
    environment:
      - ZETACORED_REPLICAS=4

  zetacore2:
    image: zetanode:latest
    container_name: zetacore2
    hostname: zetacore2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.13
    entrypoint: [ "/root/start-zetacored.sh", "4" ]
    environment:
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only
      - ZETACORED_REPLICAS=4

  zetacore3:
    image: zetanode:latest
    container_name: zetacore3
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetacore3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.14
    entrypoint: [ "/root/start-zetacored.sh", "4" ]
    environment:
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only
      - ZETACORED_REPLICAS=4

  zetaclient2:
    image: zetanode:latest
    container_name: zetaclient2
    hostname: zetaclient2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.23
    entrypoint: /root/start-zetaclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only
    volumes:
      - ssh:/root/.ssh
      - preparams:/root/preparams

  zetaclient3:
    image: zetanode:latest
    container_name: zetaclient3
    hostname: zetaclient3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.24
    entrypoint: /root/start-zetaclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only
    volumes:
      - ssh:/root/.ssh
      - preparams:/root/preparams
