version: "3"

# This docker-compose redefine the services:
# - ZetaChain with 2 nodes (zetacore0, zetacore1) using the upgrade option for cosmovisor
# - ZetaChain observer set with 2 clients (zetaclient0, zetaclient1) using the background option
# - Orchestrator with upgrade option

services:
  zetacore0:
    image: zetanode:old

  zetacore1:
    image: zetanode:old

  zetaclient0:
    entrypoint: ["/root/start-zetaclientd.sh", "background"]
    image: zetanode:old

  zetaclient1:
    entrypoint: ["/root/start-zetaclientd.sh", "background"]
    image: zetanode:old

  orchestrator:
    entrypoint: ["/work/start-zetae2e.sh", "local", "upgrade"]
    image: orchestrator

  upgrade-host:
    image: zetanode:latest
    container_name: upgrade-host
    hostname: upgrade-host
    entrypoint: ["/root/start-upgrade-host.sh"]
    networks:
      mynetwork:
        ipv4_address: 172.20.0.250
    volumes:
      - ssh:/root/.ssh

  upgrade-orchestrator:
    # must run from old node for api compatibility
    image: zetanode:old
    container_name: upgrade-orchestrator
    hostname: upgrade-orchestrator
    entrypoint: ["/root/start-upgrade-orchestrator.sh", "225"]
    networks:
      mynetwork:
        ipv4_address: 172.20.0.251
    depends_on:
      - zetacore0
      - upgrade-host
    volumes:
      - ssh:/root/.ssh