# This docker-compose file overrides the orchestrator service to specify the flag to test the admin functions
# and skip the regular tests
# it also adds another local Ethereum network to test EVM chain migration and use the additional-evm flag

services:
  eth2:
    build:
      context: ./anvil
    container_name: eth2
    hostname: eth2
    platform: linux/amd64
    ports:
      - "8546:8545"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.102

  zetaclient0:
    environment:
      - ADDITIONAL_EVM=true

  zetaclient1:
    environment:
      - ADDITIONAL_EVM=true
