version: "3"

# This docker-compose file configures the localnet environment
# it contains the following services:
# - ZetaChain with 2 nodes (zetacore0, zetacore1)
# - A observer set with 2 clients (zetaclient0, zetaclient1)
# - An Ethereum node (eth)
# - A Bitcoin node (bitcoin)
# - A Rosetta API (rosetta)
# - An orchestrator to manage interaction with the localnet (orchestrator)

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  rosetta:
    entrypoint: ["zetacored", "rosetta", "--tendermint", "zetacore0:26657", "--grpc", "zetacore0:9090", "--network", "athens_101-1", "--blockchain",  "zetacore" ,"--retries", "500"]


  zetacore0:
    entrypoint: ["/root/start-zetacored.sh", "2","import-data"]
    volumes:
      - ~/genesis_export/:/root/genesis_data

  zetacore1:
    entrypoint: ["/root/start-zetacored.sh", "2","import-data"]

  zetaclient0:
    entrypoint: ["/root/start-zetaclientd.sh", "import-data"]

  zetaclient1:
    entrypoint: ["/root/start-zetaclientd.sh", "import-data"]

  orchestrator:
    entrypoint: ["/work/start-zetae2e.sh", "local","import-data"]