# This docker-compose updates the services to use a persistent data directory
# clear these volumes with this command: docker volume rm $(docker volume ls -q | grep -- '-persist$')

services:
  zetacore0:
    volumes:
      - zetacore0-zetacored-persist:/root/.zetacored

  zetacore1:
    volumes:
      - zetacore1-zetacored-persist:/root/.zetacored

  zetacore2:
    volumes:
      - zetacore2-zetacored-persist:/root/.zetacored

  zetacore3:
    volumes:
      - zetacore3-zetacored-persist:/root/.zetacored

  zetaclient0:
    volumes:
      - zetaclient0-zetacored-persist:/root/.zetacored
      - zetaclient0-tss-persist:/root/.tss
      - zetaclient0-zetaclient-persist:/root/.zetaclient

  zetaclient1:
    volumes:
      - zetaclient1-zetacored-persist:/root/.zetacored
      - zetaclient1-tss-persist:/root/.tss
      - zetaclient1-zetaclient-persist:/root/.zetaclient

  zetaclient2:
    volumes:
      - zetaclient2-zetacored-persist:/root/.zetacored
      - zetaclient2-tss-persist:/root/.tss
      - zetaclient2-zetaclient-persist:/root/.zetaclient

  zetaclient3:
    volumes:
      - zetaclient3-zetacored-persist:/root/.zetacored
      - zetaclient3-tss-persist:/root/.tss
      - zetaclient3-zetaclient-persist:/root/.zetaclient

  eth:
    volumes:
      - eth-data-persist:/root/data

  solana:
    volumes:
      - solana-ledger-persist:/data/test-ledger
    profiles:
      - solana
      - all

  orchestrator:
    volumes:
      - orchestrator-state-persist:/root/state

volumes:
  zetacore0-zetacored-persist:
    labels:
      - "localnet=true"
  zetacore1-zetacored-persist:
    labels:
      - "localnet=true"
  zetacore2-zetacored-persist:
    labels:
      - "localnet=true"
  zetacore3-zetacored-persist:
    labels:
      - "localnet=true"
  zetaclient0-zetacored-persist:
    labels:
      - "localnet=true"
  zetaclient0-tss-persist:
    labels:
      - "localnet=true"
  zetaclient0-zetaclient-persist:
    labels:
      - "localnet=true"
  zetaclient1-zetacored-persist:
    labels:
      - "localnet=true"
  zetaclient1-tss-persist:
    labels:
      - "localnet=true"
  zetaclient1-zetaclient-persist:
    labels:
      - "localnet=true"
  zetaclient2-zetacored-persist:
    labels:
      - "localnet=true"
  zetaclient2-tss-persist:
    labels:
      - "localnet=true"
  zetaclient2-zetaclient-persist:
    labels:
      - "localnet=true"
  zetaclient3-zetacored-persist:
    labels:
      - "localnet=true"
  zetaclient3-tss-persist:
    labels:
      - "localnet=true"
  zetaclient3-zetaclient-persist:
    labels:
      - "localnet=true"
  eth-data-persist:
    labels:
      - "localnet=true"
  orchestrator-state-persist:
    labels:
      - "localnet=true"
  solana-ledger-persist:
    labels:
      - "localnet=true"
