name: "NIGHTLY:EVM:PERFORMANCE:TESTING"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  nightly_evm_api_performance_test:
    name: "NIGHTLY:EVM:API:PERFORMANCE:TEST"
    runs-on: "buildjet-16vcpu-ubuntu-2204"
    steps:
      - uses: actions/checkout@v4

      - name: "INSTALL:NODEJS"
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: "START:LOCAL:NET"
        run: | 
          make start-e2e-test

      - name: "TEST:LOCAL:NET:ALIVE"
        run: | 
          curl -X POST http://localhost:9545/ \
               -H "Content-Type: application/json" \
               -d '{
                     "id": 1,
                     "jsonrpc": "2.0",
                     "method": "web3_clientVersion",
                     "params": []
                   }'

      - name: "INSTALL:ARTILLERY"
        run: | 
          npm install -g artillery@latest

      - name: "EXECUTE:PERFORMANCE:TESTS"
        run: | 
          artillery run .github/actions/performance-tests/art.yaml --record --key ${{ secrets.ARTILLERY_KEY }} --output ./report.json

      - name: "GENERATE:REPORT"
        run: | 
          artillery report report.json --output artillery_report.html

      - name: "UPLOAD:REPORT"
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: artillery-report
          path: ./artillery_report.html