name: e2e

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  e2e:
    strategy:
      matrix:
        include:
          - make-target: "start-e2e-test"
            runs-on: ubuntu-20.04
            run: true
          - make-target: "start-upgrade-test-light"
            runs-on: ubuntu-20.04
            run: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'MINIMAL_CI') }}
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      make-target: ${{ matrix.make-target }}
      runs-on: ${{ matrix.runs-on}}
      run: ${{ matrix.run }}
    secrets: inherit
  ok:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - run: echo "e2e tests passed"
