name: Generated Files are Updated
on:
  merge_group:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Add protoc plugins to PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install solc-select
        run: |
          pip3 install solc-select

      - name: Generate Go code, docs and specs
        env:
          TEST_ENV: ${{ github.workspace }}
        run: make generate

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "::error::Generated files are not up-to-date. Please run 'make generate' locally and commit any changes."
            git status --porcelain
            git diff
            exit 1
          fi
