name: Generated Files are Updated
on:
  merge_group:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1

      - name: Add protoc plugins to PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Print solc version
        run: |
          solc --version

      - name: Run solc and capture output
        run: |
          solc IPrototype.sol --combined-json abi 2>&1 | tee solc_output.log
          cat solc_output.log

      - name: Extract ABI from JSON
        run: |
          cat IPrototype.json | jq .abi > IPrototype.abi

      - name: Run abigen and capture errors
        run: |
          abigen --abi ./precompiles/prototype/IPrototype.abi --pkg prototype --type IPrototype --out ./precompiles/prototype/IPrototype.go 2>&1 | tee abigen_output.log
          cat abigen_output.log

      - name: Generate Go code, docs and specs
        env:
          TEST_ENV: ${{ github.workspace }}
        run: make generate

      - name: Check for changes
        run: |
          if git diff --exit-code --ignore-space-change --ignore-all-space --ignore-cr-at-eol; then
            echo "Generated Go files are up-to-date."
          else
            echo "::error::Generated files are not up-to-date. Please run 'make generate' locally and commit any changes."
            exit 1
          fi
