name: Simulation Tests Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      test-target:
        description: 'Makefile test target to run (e.g., test-sim-nondeterminism)'
        required: true
        default: 'test-sim-fullappsimulation'

concurrency:
  group: runsim-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install runsim and dependencies
        run: |
          make runsim

  run-simulation-tests:
    needs: install-dependencies
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test-target: [
          "test-sim-nondeterminism",
          "test-sim-fullappsimulation",
          "test-sim-import-export",
          "test-sim-after-import"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Simulation Test - ${{ matrix.test-target }}
        run: |
          make ${{ matrix.test-target }}

  manual-run:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Simulation Test - ${{ github.event.inputs.test-target }}
        run: |
          make ${{ github.event.inputs.test-target }}
